server:
  port: 8082
spring:
  boot:
    admin:
      client:
        instance:
          service-base-url: "http://localhost:8082"
        url: "http://localhost:8090"
  task:
    scheduling:
      pool:
        size: 20
      thread-name-prefix: "task-schedule-"
management:
  endpoints:
    web:
      exposure:
        include: "*"

