
spring:
  boot:
    admin:
      client:
        instance:
          service-base-url: "http://localhost:8081"
        url: "http://localhost:8090"
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081